//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ThemeProvider } from "./context/theme";
import NavBar from "../components/nav/navbar";

export const metadata = {
  title: "zl171",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <ThemeProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
